apiVersion: apps/v1
kind: ReplicaSet
metadata: 
    name: todoappreplica1
    labels: 
      app: todoappreplica1
spec: 
    replicas: 2
    template:
      metadata: 
         labels: 
            app: todoappreplica1
      spec:
        containers:
            - name: mypod-cont1
              image: nginx:latest
              resources: 
                  requests:
                    cpu: "50m"
                    memory: "90Mi"        
              ports:  
                - name: http
                  containerPort: 80
                  protocol: TCP      
    selector: 
         matchExpressions: 
            - {key: app, operator: NotIn, values: [todoappreplica, mobappreplica]}